// Code generated by mockery v2.53.6. DO NOT EDIT.

package index

import (
	core "github.com/deagy/recall/core"
	mock "github.com/stretchr/testify/mock"
)

// MockFilter is an autogenerated mock type for the Filter type
type MockFilter struct {
	mock.Mock
}

// Match provides a mock function with given fields: chunk
func (_m *MockFilter) Match(chunk *core.Chunk) bool {
	ret := _m.Called(chunk)

	if len(ret) == 0 {
		panic("no return value specified for Match")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(*core.Chunk) bool); ok {
		r0 = rf(chunk)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewMockFilter creates a new instance of MockFilter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFilter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFilter {
	mock := &MockFilter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
