// Code generated by mockery v2.53.6. DO NOT EDIT.

package index

import (
	context "context"

	core "github.com/deagy/recall/core"
	mock "github.com/stretchr/testify/mock"
)

// MockIndex is an autogenerated mock type for the Index type
type MockIndex struct {
	mock.Mock
}

// Add provides a mock function with given fields: ctx, chunk
func (_m *MockIndex) Add(ctx context.Context, chunk *core.Chunk) error {
	ret := _m.Called(ctx, chunk)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *core.Chunk) error); ok {
		r0 = rf(ctx, chunk)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddBatch provides a mock function with given fields: ctx, chunks
func (_m *MockIndex) AddBatch(ctx context.Context, chunks []*core.Chunk) error {
	ret := _m.Called(ctx, chunks)

	if len(ret) == 0 {
		panic("no return value specified for AddBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*core.Chunk) error); ok {
		r0 = rf(ctx, chunks)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Count provides a mock function with no fields
func (_m *MockIndex) Count() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockIndex) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Dimension provides a mock function with no fields
func (_m *MockIndex) Dimension() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Dimension")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// Namespace provides a mock function with no fields
func (_m *MockIndex) Namespace() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Namespace")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Search provides a mock function with given fields: ctx, query, opts
func (_m *MockIndex) Search(ctx context.Context, query []float32, opts SearchOptions) ([]SearchResult, error) {
	ret := _m.Called(ctx, query, opts)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []SearchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []float32, SearchOptions) ([]SearchResult, error)); ok {
		return rf(ctx, query, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []float32, SearchOptions) []SearchResult); ok {
		r0 = rf(ctx, query, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]SearchResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []float32, SearchOptions) error); ok {
		r1 = rf(ctx, query, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockIndex creates a new instance of MockIndex. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIndex(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIndex {
	mock := &MockIndex{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
