// Code generated by mockery v2.53.6. DO NOT EDIT.

package store

import (
	context "context"

	graph "github.com/deagy/recall/graph"
	mock "github.com/stretchr/testify/mock"
)

// MockGraphStore is an autogenerated mock type for the GraphStore type
type MockGraphStore struct {
	mock.Mock
}

// CommonNeighbors provides a mock function with given fields: id1, id2
func (_m *MockGraphStore) CommonNeighbors(id1 string, id2 string) []*graph.Entity {
	ret := _m.Called(id1, id2)

	if len(ret) == 0 {
		panic("no return value specified for CommonNeighbors")
	}

	var r0 []*graph.Entity
	if rf, ok := ret.Get(0).(func(string, string) []*graph.Entity); ok {
		r0 = rf(id1, id2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*graph.Entity)
		}
	}

	return r0
}

// Count provides a mock function with no fields
func (_m *MockGraphStore) Count() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// Entities provides a mock function with no fields
func (_m *MockGraphStore) Entities() graph.Entities {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Entities")
	}

	var r0 graph.Entities
	if rf, ok := ret.Get(0).(func() graph.Entities); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(graph.Entities)
		}
	}

	return r0
}

// ExtractEntities provides a mock function with given fields: ctx, text, sourceChunkID
func (_m *MockGraphStore) ExtractEntities(ctx context.Context, text string, sourceChunkID string) ([]*graph.Entity, error) {
	ret := _m.Called(ctx, text, sourceChunkID)

	if len(ret) == 0 {
		panic("no return value specified for ExtractEntities")
	}

	var r0 []*graph.Entity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]*graph.Entity, error)); ok {
		return rf(ctx, text, sourceChunkID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []*graph.Entity); ok {
		r0 = rf(ctx, text, sourceChunkID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*graph.Entity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, text, sourceChunkID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExtractRelations provides a mock function with given fields: ctx, text, sourceChunkID
func (_m *MockGraphStore) ExtractRelations(ctx context.Context, text string, sourceChunkID string) ([]*graph.Relation, error) {
	ret := _m.Called(ctx, text, sourceChunkID)

	if len(ret) == 0 {
		panic("no return value specified for ExtractRelations")
	}

	var r0 []*graph.Relation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]*graph.Relation, error)); ok {
		return rf(ctx, text, sourceChunkID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []*graph.Relation); ok {
		r0 = rf(ctx, text, sourceChunkID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*graph.Relation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, text, sourceChunkID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindEntitiesByLabel provides a mock function with given fields: query
func (_m *MockGraphStore) FindEntitiesByLabel(query string) graph.Entities {
	ret := _m.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for FindEntitiesByLabel")
	}

	var r0 graph.Entities
	if rf, ok := ret.Get(0).(func(string) graph.Entities); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(graph.Entities)
		}
	}

	return r0
}

// FindEntitiesByType provides a mock function with given fields: typ
func (_m *MockGraphStore) FindEntitiesByType(typ graph.EntityType) graph.Entities {
	ret := _m.Called(typ)

	if len(ret) == 0 {
		panic("no return value specified for FindEntitiesByType")
	}

	var r0 graph.Entities
	if rf, ok := ret.Get(0).(func(graph.EntityType) graph.Entities); ok {
		r0 = rf(typ)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(graph.Entities)
		}
	}

	return r0
}

// FindPath provides a mock function with given fields: from, to
func (_m *MockGraphStore) FindPath(from string, to string) *graph.Path {
	ret := _m.Called(from, to)

	if len(ret) == 0 {
		panic("no return value specified for FindPath")
	}

	var r0 *graph.Path
	if rf, ok := ret.Get(0).(func(string, string) *graph.Path); ok {
		r0 = rf(from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*graph.Path)
		}
	}

	return r0
}

// GetEntity provides a mock function with given fields: id
func (_m *MockGraphStore) GetEntity(id string) (*graph.Entity, bool) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetEntity")
	}

	var r0 *graph.Entity
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (*graph.Entity, bool)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *graph.Entity); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*graph.Entity)
		}
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// GetRelation provides a mock function with given fields: from, to, relType
func (_m *MockGraphStore) GetRelation(from string, to string, relType string) (*graph.Relation, bool) {
	ret := _m.Called(from, to, relType)

	if len(ret) == 0 {
		panic("no return value specified for GetRelation")
	}

	var r0 *graph.Relation
	var r1 bool
	if rf, ok := ret.Get(0).(func(string, string, string) (*graph.Relation, bool)); ok {
		return rf(from, to, relType)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) *graph.Relation); ok {
		r0 = rf(from, to, relType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*graph.Relation)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string) bool); ok {
		r1 = rf(from, to, relType)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// Graph provides a mock function with no fields
func (_m *MockGraphStore) Graph() *graph.KnowledgeGraph {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Graph")
	}

	var r0 *graph.KnowledgeGraph
	if rf, ok := ret.Get(0).(func() *graph.KnowledgeGraph); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*graph.KnowledgeGraph)
		}
	}

	return r0
}

// Neighbors provides a mock function with given fields: entityID
func (_m *MockGraphStore) Neighbors(entityID string) []*graph.Entity {
	ret := _m.Called(entityID)

	if len(ret) == 0 {
		panic("no return value specified for Neighbors")
	}

	var r0 []*graph.Entity
	if rf, ok := ret.Get(0).(func(string) []*graph.Entity); ok {
		r0 = rf(entityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*graph.Entity)
		}
	}

	return r0
}

// RelationCount provides a mock function with no fields
func (_m *MockGraphStore) RelationCount() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RelationCount")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// Relations provides a mock function with no fields
func (_m *MockGraphStore) Relations() graph.Relations {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Relations")
	}

	var r0 graph.Relations
	if rf, ok := ret.Get(0).(func() graph.Relations); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(graph.Relations)
		}
	}

	return r0
}

// ShortestPathLength provides a mock function with given fields: from, to
func (_m *MockGraphStore) ShortestPathLength(from string, to string) int {
	ret := _m.Called(from, to)

	if len(ret) == 0 {
		panic("no return value specified for ShortestPathLength")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func(string, string) int); ok {
		r0 = rf(from, to)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// TransitiveClosure provides a mock function with given fields: entityID
func (_m *MockGraphStore) TransitiveClosure(entityID string) []*graph.Entity {
	ret := _m.Called(entityID)

	if len(ret) == 0 {
		panic("no return value specified for TransitiveClosure")
	}

	var r0 []*graph.Entity
	if rf, ok := ret.Get(0).(func(string) []*graph.Entity); ok {
		r0 = rf(entityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*graph.Entity)
		}
	}

	return r0
}

// NewMockGraphStore creates a new instance of MockGraphStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGraphStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGraphStore {
	mock := &MockGraphStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
