// Code generated by mockery v2.53.6. DO NOT EDIT.

package store

import (
	graph "github.com/deagy/recall/graph"
	mock "github.com/stretchr/testify/mock"
)

// MockGraphPersistence is an autogenerated mock type for the GraphPersistence type
type MockGraphPersistence struct {
	mock.Mock
}

// AddEntity provides a mock function with given fields: e
func (_m *MockGraphPersistence) AddEntity(e *graph.Entity) error {
	ret := _m.Called(e)

	if len(ret) == 0 {
		panic("no return value specified for AddEntity")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*graph.Entity) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddRelation provides a mock function with given fields: r
func (_m *MockGraphPersistence) AddRelation(r *graph.Relation) error {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for AddRelation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*graph.Relation) error); ok {
		r0 = rf(r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Clear provides a mock function with no fields
func (_m *MockGraphPersistence) Clear() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Clear")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Close provides a mock function with no fields
func (_m *MockGraphPersistence) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LoadFromDB provides a mock function with no fields
func (_m *MockGraphPersistence) LoadFromDB() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LoadFromDB")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockGraphPersistence creates a new instance of MockGraphPersistence. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGraphPersistence(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGraphPersistence {
	mock := &MockGraphPersistence{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
