// Code generated by mockery v2.53.6. DO NOT EDIT.

package store

import (
	context "context"

	core "github.com/deagy/recall/core"
	index "github.com/deagy/recall/index"

	mock "github.com/stretchr/testify/mock"
)

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *MockStore) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Count provides a mock function with no fields
func (_m *MockStore) Count() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// DeleteChunk provides a mock function with given fields: id
func (_m *MockStore) DeleteChunk(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteChunk")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteDocument provides a mock function with given fields: docID
func (_m *MockStore) DeleteDocument(docID string) error {
	ret := _m.Called(docID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDocument")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(docID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetChunk provides a mock function with given fields: id
func (_m *MockStore) GetChunk(id string) (*core.Chunk, bool) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetChunk")
	}

	var r0 *core.Chunk
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (*core.Chunk, bool)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *core.Chunk); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Chunk)
		}
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// Namespaces provides a mock function with no fields
func (_m *MockStore) Namespaces() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Namespaces")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// Search provides a mock function with given fields: ctx, query, opts
func (_m *MockStore) Search(ctx context.Context, query string, opts index.SearchOptions) ([]index.SearchResult, error) {
	ret := _m.Called(ctx, query, opts)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []index.SearchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, index.SearchOptions) ([]index.SearchResult, error)); ok {
		return rf(ctx, query, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, index.SearchOptions) []index.SearchResult); ok {
		r0 = rf(ctx, query, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]index.SearchResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, index.SearchOptions) error); ok {
		r1 = rf(ctx, query, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchHybrid provides a mock function with given fields: ctx, query, opts
func (_m *MockStore) SearchHybrid(ctx context.Context, query string, opts index.SearchOptions) ([]index.SearchResult, error) {
	ret := _m.Called(ctx, query, opts)

	if len(ret) == 0 {
		panic("no return value specified for SearchHybrid")
	}

	var r0 []index.SearchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, index.SearchOptions) ([]index.SearchResult, error)); ok {
		return rf(ctx, query, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, index.SearchOptions) []index.SearchResult); ok {
		r0 = rf(ctx, query, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]index.SearchResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, index.SearchOptions) error); ok {
		r1 = rf(ctx, query, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upload provides a mock function with given fields: ctx, doc, content
func (_m *MockStore) Upload(ctx context.Context, doc *core.Document, content string) error {
	ret := _m.Called(ctx, doc, content)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *core.Document, string) error); ok {
		r0 = rf(ctx, doc, content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
