// Code generated by mockery v2.53.6. DO NOT EDIT.

package graph

import mock "github.com/stretchr/testify/mock"

// MockNERExtractor is an autogenerated mock type for the NERExtractor type
type MockNERExtractor struct {
	mock.Mock
}

// Extract provides a mock function with given fields: text
func (_m *MockNERExtractor) Extract(text string) ([]*Entity, error) {
	ret := _m.Called(text)

	if len(ret) == 0 {
		panic("no return value specified for Extract")
	}

	var r0 []*Entity
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*Entity, error)); ok {
		return rf(text)
	}
	if rf, ok := ret.Get(0).(func(string) []*Entity); ok {
		r0 = rf(text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Entity)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(text)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockNERExtractor creates a new instance of MockNERExtractor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNERExtractor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNERExtractor {
	mock := &MockNERExtractor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
