// Code generated by mockery v2.53.6. DO NOT EDIT.

package core

import mock "github.com/stretchr/testify/mock"

// MockValue is an autogenerated mock type for the Value type
type MockValue struct {
	mock.Mock
}

// Kind provides a mock function with no fields
func (_m *MockValue) Kind() ValueKind {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Kind")
	}

	var r0 ValueKind
	if rf, ok := ret.Get(0).(func() ValueKind); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(ValueKind)
	}

	return r0
}

// String provides a mock function with no fields
func (_m *MockValue) String() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewMockValue creates a new instance of MockValue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockValue(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockValue {
	mock := &MockValue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
