// Code generated by mockery v2.53.6. DO NOT EDIT.

package reasoning

import (
	graph "github.com/deagy/recall/graph"
	mock "github.com/stretchr/testify/mock"
)

// MockInferenceRule is an autogenerated mock type for the InferenceRule type
type MockInferenceRule struct {
	mock.Mock
}

// Apply provides a mock function with given fields: rel
func (_m *MockInferenceRule) Apply(rel *graph.Relation) (*graph.Relation, bool) {
	ret := _m.Called(rel)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 *graph.Relation
	var r1 bool
	if rf, ok := ret.Get(0).(func(*graph.Relation) (*graph.Relation, bool)); ok {
		return rf(rel)
	}
	if rf, ok := ret.Get(0).(func(*graph.Relation) *graph.Relation); ok {
		r0 = rf(rel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*graph.Relation)
		}
	}

	if rf, ok := ret.Get(1).(func(*graph.Relation) bool); ok {
		r1 = rf(rel)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// Name provides a mock function with no fields
func (_m *MockInferenceRule) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewMockInferenceRule creates a new instance of MockInferenceRule. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInferenceRule(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInferenceRule {
	mock := &MockInferenceRule{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
