// Code generated by mockery v2.53.6. DO NOT EDIT.

package chunker

import (
	core "github.com/deagy/recall/core"
	mock "github.com/stretchr/testify/mock"
)

// MockChunker is an autogenerated mock type for the Chunker type
type MockChunker struct {
	mock.Mock
}

// Chunk provides a mock function with given fields: doc, content
func (_m *MockChunker) Chunk(doc *core.Document, content string) ([]*core.Chunk, error) {
	ret := _m.Called(doc, content)

	if len(ret) == 0 {
		panic("no return value specified for Chunk")
	}

	var r0 []*core.Chunk
	var r1 error
	if rf, ok := ret.Get(0).(func(*core.Document, string) ([]*core.Chunk, error)); ok {
		return rf(doc, content)
	}
	if rf, ok := ret.Get(0).(func(*core.Document, string) []*core.Chunk); ok {
		r0 = rf(doc, content)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*core.Chunk)
		}
	}

	if rf, ok := ret.Get(1).(func(*core.Document, string) error); ok {
		r1 = rf(doc, content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockChunker creates a new instance of MockChunker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChunker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChunker {
	mock := &MockChunker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
