// Code generated by mockery v2.53.6. DO NOT EDIT.

package chunker

import mock "github.com/stretchr/testify/mock"

// MockFactory is an autogenerated mock type for the Factory type
type MockFactory struct {
	mock.Mock
}

// Execute provides a mock function with given fields: cfg
func (_m *MockFactory) Execute(cfg Config) Chunker {
	ret := _m.Called(cfg)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 Chunker
	if rf, ok := ret.Get(0).(func(Config) Chunker); ok {
		r0 = rf(cfg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Chunker)
		}
	}

	return r0
}

// NewMockFactory creates a new instance of MockFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFactory {
	mock := &MockFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
