// Code generated by mockery v2.53.6. DO NOT EDIT.

package fuse

import mock "github.com/stretchr/testify/mock"

// MockFusion is an autogenerated mock type for the Fusion type
type MockFusion struct {
	mock.Mock
}

// Fuse provides a mock function with given fields: scores
func (_m *MockFusion) Fuse(scores ...map[string]float64) map[string]float64 {
	_va := make([]interface{}, len(scores))
	for _i := range scores {
		_va[_i] = scores[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Fuse")
	}

	var r0 map[string]float64
	if rf, ok := ret.Get(0).(func(...map[string]float64) map[string]float64); ok {
		r0 = rf(scores...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]float64)
		}
	}

	return r0
}

// NewMockFusion creates a new instance of MockFusion. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFusion(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFusion {
	mock := &MockFusion{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
